# Generated by Django 5.1.6 on 2025-02-25 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('eye_color', models.CharField(choices=[('blu', 'Blue'), ('blk', 'Black'), ('bro', 'Brown'), ('grn', 'Green')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(choices=[('art', 'Art'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('eng', 'English'), ('hist', 'History')], max_length=4)),
                ('students', models.ManyToManyField(null=True, related_name='courses', to='students.student')),
            ],
        ),
    ]
